server:
  port: 9090

spring:
  application:
    name: micro-weather-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mokeychan/config-repo-demo
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


